name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_ubuntu:
    if: "!contains(github.event.pull_request.labels.*.name, 'docs-only')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.9', '3.11']
    steps:
      - uses: compas-dev/compas-actions.build@v3
        with:
          python: ${{ matrix.python }}
          invoke_lint: true
          invoke_test: true
      - name: install libglu
        run: apt-get install libglu

  build:
    if: "!contains(github.event.pull_request.labels.*.name, 'docs-only')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python: [ '3.9', '3.11']

    steps:
      - uses: compas-dev/compas-actions.build@v3
        with:
          python: ${{ matrix.python }}
          invoke_lint: true
          invoke_test: true
